/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedReflectionsRouteImport } from './routes/_authenticated.reflections'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated.notifications'
import { Route as AuthenticatedJournalRouteImport } from './routes/_authenticated.journal'
import { Route as AuthenticatedIncomeRouteImport } from './routes/_authenticated.income'
import { Route as AuthenticatedGoalsRouteImport } from './routes/_authenticated.goals'
import { Route as AuthenticatedDebtRouteImport } from './routes/_authenticated.debt'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedComponentShowcaseRouteImport } from './routes/_authenticated.component-showcase'
import { Route as AuthenticatedCoachRouteImport } from './routes/_authenticated.coach'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated.analytics'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated.settings.index'
import { Route as AuthenticatedSettingsDataRouteImport } from './routes/_authenticated.settings.data'
import { Route as AuthenticatedSettingsAccountsRouteImport } from './routes/_authenticated.settings.accounts'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReflectionsRoute =
  AuthenticatedReflectionsRouteImport.update({
    id: '/reflections',
    path: '/reflections',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedJournalRoute = AuthenticatedJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIncomeRoute = AuthenticatedIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGoalsRoute = AuthenticatedGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDebtRoute = AuthenticatedDebtRouteImport.update({
  id: '/debt',
  path: '/debt',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedComponentShowcaseRoute =
  AuthenticatedComponentShowcaseRouteImport.update({
    id: '/component-showcase',
    path: '/component-showcase',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCoachRoute = AuthenticatedCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsDataRoute =
  AuthenticatedSettingsDataRouteImport.update({
    id: '/data',
    path: '/data',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAccountsRoute =
  AuthenticatedSettingsAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/coach': typeof AuthenticatedCoachRoute
  '/component-showcase': typeof AuthenticatedComponentShowcaseRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/debt': typeof AuthenticatedDebtRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/income': typeof AuthenticatedIncomeRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/reflections': typeof AuthenticatedReflectionsRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/settings/accounts': typeof AuthenticatedSettingsAccountsRoute
  '/settings/data': typeof AuthenticatedSettingsDataRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/coach': typeof AuthenticatedCoachRoute
  '/component-showcase': typeof AuthenticatedComponentShowcaseRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/debt': typeof AuthenticatedDebtRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/income': typeof AuthenticatedIncomeRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/reflections': typeof AuthenticatedReflectionsRoute
  '/settings/accounts': typeof AuthenticatedSettingsAccountsRoute
  '/settings/data': typeof AuthenticatedSettingsDataRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/coach': typeof AuthenticatedCoachRoute
  '/_authenticated/component-showcase': typeof AuthenticatedComponentShowcaseRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/debt': typeof AuthenticatedDebtRoute
  '/_authenticated/goals': typeof AuthenticatedGoalsRoute
  '/_authenticated/income': typeof AuthenticatedIncomeRoute
  '/_authenticated/journal': typeof AuthenticatedJournalRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/reflections': typeof AuthenticatedReflectionsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/settings/accounts': typeof AuthenticatedSettingsAccountsRoute
  '/_authenticated/settings/data': typeof AuthenticatedSettingsDataRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/analytics'
    | '/coach'
    | '/component-showcase'
    | '/dashboard'
    | '/debt'
    | '/goals'
    | '/income'
    | '/journal'
    | '/notifications'
    | '/reflections'
    | '/settings'
    | '/settings/accounts'
    | '/settings/data'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/analytics'
    | '/coach'
    | '/component-showcase'
    | '/dashboard'
    | '/debt'
    | '/goals'
    | '/income'
    | '/journal'
    | '/notifications'
    | '/reflections'
    | '/settings/accounts'
    | '/settings/data'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/analytics'
    | '/_authenticated/coach'
    | '/_authenticated/component-showcase'
    | '/_authenticated/dashboard'
    | '/_authenticated/debt'
    | '/_authenticated/goals'
    | '/_authenticated/income'
    | '/_authenticated/journal'
    | '/_authenticated/notifications'
    | '/_authenticated/reflections'
    | '/_authenticated/settings'
    | '/_authenticated/settings/accounts'
    | '/_authenticated/settings/data'
    | '/_authenticated/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reflections': {
      id: '/_authenticated/reflections'
      path: '/reflections'
      fullPath: '/reflections'
      preLoaderRoute: typeof AuthenticatedReflectionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/journal': {
      id: '/_authenticated/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AuthenticatedJournalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/income': {
      id: '/_authenticated/income'
      path: '/income'
      fullPath: '/income'
      preLoaderRoute: typeof AuthenticatedIncomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/goals': {
      id: '/_authenticated/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AuthenticatedGoalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/debt': {
      id: '/_authenticated/debt'
      path: '/debt'
      fullPath: '/debt'
      preLoaderRoute: typeof AuthenticatedDebtRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/component-showcase': {
      id: '/_authenticated/component-showcase'
      path: '/component-showcase'
      fullPath: '/component-showcase'
      preLoaderRoute: typeof AuthenticatedComponentShowcaseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/coach': {
      id: '/_authenticated/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AuthenticatedCoachRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/data': {
      id: '/_authenticated/settings/data'
      path: '/data'
      fullPath: '/settings/data'
      preLoaderRoute: typeof AuthenticatedSettingsDataRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/accounts': {
      id: '/_authenticated/settings/accounts'
      path: '/accounts'
      fullPath: '/settings/accounts'
      preLoaderRoute: typeof AuthenticatedSettingsAccountsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
  }
}

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsAccountsRoute: typeof AuthenticatedSettingsAccountsRoute
  AuthenticatedSettingsDataRoute: typeof AuthenticatedSettingsDataRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsAccountsRoute: AuthenticatedSettingsAccountsRoute,
  AuthenticatedSettingsDataRoute: AuthenticatedSettingsDataRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedCoachRoute: typeof AuthenticatedCoachRoute
  AuthenticatedComponentShowcaseRoute: typeof AuthenticatedComponentShowcaseRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDebtRoute: typeof AuthenticatedDebtRoute
  AuthenticatedGoalsRoute: typeof AuthenticatedGoalsRoute
  AuthenticatedIncomeRoute: typeof AuthenticatedIncomeRoute
  AuthenticatedJournalRoute: typeof AuthenticatedJournalRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedReflectionsRoute: typeof AuthenticatedReflectionsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedCoachRoute: AuthenticatedCoachRoute,
  AuthenticatedComponentShowcaseRoute: AuthenticatedComponentShowcaseRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDebtRoute: AuthenticatedDebtRoute,
  AuthenticatedGoalsRoute: AuthenticatedGoalsRoute,
  AuthenticatedIncomeRoute: AuthenticatedIncomeRoute,
  AuthenticatedJournalRoute: AuthenticatedJournalRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedReflectionsRoute: AuthenticatedReflectionsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
